version: '3'

services:
  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example

  backend:
    image: "node:8"
    user: "node"
    working_dir: /home/node/app
    environment:
      - NODE_ENV=production
    volumes:
      - ./backend:/home/node/app
    expose:
      - '3000'
    command: "npm install"
    command: "node app.js"

  frontend:
    image: httpd:2.4
    volumes: 
      - ./frontend/build/:/usr/local/apache2/htdocs/
    ports:
      - 80:80